services:
  - type: web
    runtime: docker
    name: english-site
    rootDir: english
    plan: free
    autoDeploy: true
    healthCheckPath: /
    region: singapore
  - type: web
    runtime: docker
    name: korean-site
    rootDir: korean
    plan: free
    autoDeploy: true
    healthCheckPath: /
    region: singapore
  - type: web
    runtime: docker
    name: japanese-site
    rootDir: Japanese
    plan: free
    autoDeploy: true
    healthCheckPath: /
    region: singapore